//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_work
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отделы_предприятия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Отделы_предприятия()
        {
            this.Задачи_отделов = new HashSet<Задачи_отделов>();
            this.Сотрудники_отделов = new HashSet<Сотрудники_отделов>();
        }
    
        public int id { get; set; }
        public string Название_отдела { get; set; }
        public string Адрес { get; set; }
        public string Контактные_данные { get; set; }
        public string Роль_отдела { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Задачи_отделов> Задачи_отделов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сотрудники_отделов> Сотрудники_отделов { get; set; }
    }
}
