//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_work
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники_отделов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники_отделов()
        {
            this.Задачи_отделов = new HashSet<Задачи_отделов>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_отдела { get; set; }
        public string ФИО { get; set; }
        public string Должность { get; set; }
        public string Контактные_данные { get; set; }
        public Nullable<decimal> Зарплата { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool Admin { get; set; }
        public bool Ruk { get; set; }
        public bool Sot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Задачи_отделов> Задачи_отделов { get; set; }
        public virtual Отделы_предприятия Отделы_предприятия { get; set; }
    }
}
